"""post-table-phone-column

Revision ID: 3409eafc1c07
Revises: 495c5ba371b7
Create Date: 2021-11-04 23:13:00.061347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3409eafc1c07'
down_revision = '495c5ba371b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone')
    # ### end Alembic commands ###
